apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
          resources:
            limits:
              memory: 2Gi
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            #  - name: discovery.type
            #  value: single-node
            - name: discovery.seed_hosts         # Add this line
              value: "192.168.1.8"             # Use the service name
                #    - name: discovery.seed_providers     # Add this line
                #   value: "seeds"                     # Use the default value 'seeds'
            - name: cluster.initial_master_nodes # Add this line
              value: "192.168.1.8"  # Replace with your pod name

